[project]
name = "omniavelis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "omnicoreagent>=0.2.10",
    "ruff>=0.14.3",
]
